#!/usr/bin/env python3
"""Silo discharge in 3D (Beverloo et al. 1961; Nedderman et al. 1982): a flat-bottomed cylindrical
silo of diameter 30 d filled to 40 d with beads of mean diameter d (+-5% polydisperse) drains
through a circular floor orifice of diameter D at the rate

    W = C rho_b sqrt(g) (D - k d)^(5/2),   C = 0.58, k = 1.4 (beads/s with rho_b in beads/m^3)

independent of the fill height (Janssen). The silo is a ConcentricCircleMeshGenerator disk whose
inner circle is the orifice, extruded along z; the floor is the extruded bottom boundary outside
the orifice (ParsedGenerateSideset), so beads falling through leave the mesh and count as exited.
Fits the exited count against time over the steady window, then W^(2/5) against D (a straight
line with x-intercept k d under Beverloo's law) and reports C, k, and the free exponent.
Usage: run.py [-n ranks] [dem-opt] [mu=..] [mu_r=..] [tag=..] [orifice diameters in bead diameters...]"""
import csv, math, os, subprocess, sys, random

here = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[1:]
ranks = 8
if args[:1] == ["-n"]:
    ranks = int(args[1])
    args = args[2:]
exe = args[0] if args and not args[0].replace(".", "").isdigit() and "=" not in args[0] else os.path.join(here, "../../dem-opt")
widths = [float(a) for a in args if a.replace(".", "").isdigit()] or [6.0, 7.0, 8.0, 10.0]
opts = dict(a.split("=") for a in args if "=" in a)      # e.g. mu=0.3 mu_r=0 tag=glass

d = 0.006                        # 6 mm beads
r = d / 2
R = 15 * d                       # silo radius: the widest orifice is a third of the diameter
H = 40 * d                       # fill height, 1.33 silo diameters: discharge starts in the Janssen regime
Hmesh = H + 8 * d
rho = 2500
g = 9.81
mu, mu_r = float(opts.get("mu", 0.5)), float(opts.get("mu_r", 0.1))
tag = opts.get("tag", "")
m = rho * 4 / 3 * math.pi * r**3
# Linear spring: the beads at the bottom of a 40 d column overlap by 40 m g / k = 0.7% of r;
# damping gives a restitution of about 0.45 (damping ratio 0.25); the substep is a 26th of the
# contact time pi / sqrt(k / m_eff) with m_eff = m / 2
k = 5e3
c = 0.25 * 2 * math.sqrt(k * m / 2)
substeps = 500
poly = 0.05                      # radius spread, enough to keep the lattice from crystallizing
random.seed(1)
# Beverloo 1961 / Nedderman 1982 constants for the number rate, with bulk density 0.6 (loose random packing)
C_ref, k_ref = 0.58, 1.4
rho_b = 0.6 / (math.pi / 6 * d**3)


def fill():
    """Hexagonal close packing of the cylinder up to height H, jittered, with random radii"""
    sx = d * (1 + poly) * 1.02        # no initial overlap even between the largest beads
    sy = sx * math.sqrt(3) / 2
    sz = sx * math.sqrt(2 / 3)
    pts, radii = [], []
    layer = 0
    z = r * 1.05
    while z < H:
        row = 0
        # B layers sit over the triangle centroids of A layers: shifted by (sx/2, sy/3)
        y = -R + (sy / 3 if layer % 2 else 0)
        while y < R:
            x = -R + (sx / 2 if (row + layer) % 2 else 0)
            while x < R:
                if math.hypot(x, y) < R - 1.1 * r:
                    pts.append((x + random.uniform(-1, 1) * 0.01 * r, y + random.uniform(-1, 1) * 0.01 * r, z))
                    radii.append(r * (1 + random.uniform(-poly, poly)))
                x += sx
            y += sy
            row += 1
        z += sz
        layer += 1
    return pts, radii


pts, radii = fill()
results = []
for Dd in widths:
    D = Dd * d
    base = f"silo3d{tag}_D{Dd:g}"
    T = 0.4 + 2500 / (C_ref * rho_b * math.sqrt(g) * (D - k_ref * d) ** 2.5)   # settling + ~2500 beads discharged
    T = min(T, 4.0)
    with open(os.path.join(here, base + ".i"), "w") as f:
        f.write(f"""# 3D silo discharge, orifice {Dd:g} d: {len(pts)} beads, generated by run.py
[Mesh]
  [disk]
    type = ConcentricCircleMeshGenerator
    num_sectors = 8
    radii = '{D / 2:.6f} {R:.6f}'
    rings = '2 {max(2, int(round((R - D / 2) / (2 * d))))}'
    has_outer_square = false
    preserve_volumes = true
    smoothing_max_it = 0
  []
  [silo]
    type = AdvancedExtruderGenerator
    input = disk
    direction = '0 0 1'
    heights = '{Hmesh:.4f}'
    num_layers = {int(round(Hmesh / (2 * d)))}
    bottom_boundary = 100
    top_boundary = 101
  []
  [floor]
    type = ParsedGenerateSideset
    input = silo
    combinatorial_geometry = 'x*x + y*y > {(D / 2) ** 2:.8f}'
    included_boundaries = 100
    new_sideset_name = floor
    replace = true
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{x:.6f} {y:.6f} {z:.6f}" for x, y, z in pts)}'
    initial_radii = '{" ".join(f"{a:.7f}" for a in radii)}'
    radius = {r}
    density = {rho}
    gravity = '0 0 -{g}'
    normal_stiffness = {k}
    normal_damping = {c}
    tangential_stiffness = {k}
    tangential_damping = {c}
    friction = {mu}
    rolling_stiffness = {k}
    rolling_damping = {c}
    rolling_friction = {mu_r}
    wall_boundaries = 'outer floor'
    skin = {r / 2}
    substeps = {substeps}
    timestep_check = error
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [exited]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_exited
  []
  [height]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_z
  []
  [floor_force]
    type = KokkosWallForce
    cloud = cloud
    boundary = floor
    component = z
  []
  [imbalance]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = load_imbalance
  []
[]
[Executioner]
  type = Transient
  dt = 0.01
  num_steps = {int(round(T / 0.01))}
[]
[Outputs]
  csv = true
  [console]
    type = Console
    execute_postprocessors_on = NONE
  []
[]
""")
    cmd = ["mpiexec", "-n", str(ranks), exe, "-i", base + ".i"] if ranks > 1 else [exe, "-i", base + ".i"]
    run = subprocess.run(cmd, cwd=here, capture_output=True, text=True)
    if run.returncode:
        print(run.stdout[-3000:], run.stderr[-2000:])
        sys.exit(1)
    rows = list(csv.DictReader(open(os.path.join(here, base + "_out.csv"))))
    t = [float(q["time"]) for q in rows]
    n = [float(q["exited"]) for q in rows]
    h = [float(q["height"]) for q in rows]
    # Steady window: after the lattice has settled onto the floor and while the free surface is
    # still above one silo diameter, where Janssen's saturation holds the floor stress
    win = [i for i in range(len(t)) if t[i] >= 0.4 and h[i] >= 2 * R]
    tw, nw = [t[i] for i in win], [n[i] for i in win]
    tm, nm = sum(tw) / len(tw), sum(nw) / len(nw)
    W = sum((a - tm) * (b - nm) for a, b in zip(tw, nw)) / sum((a - tm) ** 2 for a in tw)
    resid = math.sqrt(sum((b - nm - W * (a - tm)) ** 2 for a, b in zip(tw, nw)) / len(tw)) / max(nw[-1] - nw[0], 1)
    W_ref = C_ref * rho_b * math.sqrt(g) * (D - k_ref * d) ** 2.5
    results.append((Dd, W, resid, n[-1]))
    print(f"D = {Dd:g} d: W = {W:.0f} beads/s over t = [{tw[0]:.2f}, {tw[-1]:.2f}] s (fit residual "
          f"{100 * resid:.1f}%), Beverloo C = 0.58, k = 1.4 gives {W_ref:.0f} ({100 * (W / W_ref - 1):+.1f}%); "
          f"{int(n[-1])} of {len(pts)} exited by t = {t[-1]:.2f} s", flush=True)
if len(results) < 3:
    sys.exit(0)

# Beverloo: W^(2/5) = (C rho_b sqrt g)^(2/5) (D - k d) is linear in D with x-intercept k d
Ds = [q[0] * d for q in results]
Ws = [q[1] ** 0.4 for q in results]
Dm, Wm = sum(Ds) / len(Ds), sum(Ws) / len(Ws)
slope = sum((a - Dm) * (b - Wm) for a, b in zip(Ds, Ws)) / sum((a - Dm) ** 2 for a in Ds)
k = (Dm - Wm / slope) / d
C = slope ** 2.5 / (rho_b * math.sqrt(g))
lx = [math.log(a - k * d) for a in Ds]
ly = [math.log(q[1]) for q in results]
lxm, lym = sum(lx) / len(lx), sum(ly) / len(ly)
nexp = sum((a - lxm) * (b - lym) for a, b in zip(lx, ly)) / sum((a - lxm) ** 2 for a in lx)
print(f"Beverloo fit: C = {C:.3f} (ref 0.58), k = {k:.2f} (ref 1.4), exponent with that k: {nexp:.2f} (ref 2.5)")

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(5.5, 4.2))
    ax.plot([q[0] for q in results], Ws, "o", label="DEM")
    xx = [k, max(widths)]
    ax.plot(xx, [slope * (x * d - k * d) for x in xx], "k--", label=f"fit: C = {C:.2f}, k = {k:.2f}")
    ax.plot(xx, [(C_ref * rho_b * math.sqrt(g)) ** 0.4 * (x * d - k_ref * d) for x in xx], "r:",
            label="Beverloo: C = 0.58, k = 1.4")
    ax.set_xlabel("orifice diameter D / d")
    ax.set_ylabel("W^(2/5)  [(beads/s)^(2/5)]")
    ax.grid(alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(here, f"silo_discharge_3d{tag}.png"), dpi=130)
    print(f"plot: silo_discharge_3d{tag}.png")
except ImportError:
    pass
