#!/usr/bin/env python3
"""LAMMPS examples/pour/in.pour.2d: 1000 disks of diameter 0.5-1 (density 1, disk masses, LJ
units) poured into a 100 x 50 box with frictionless walls, gran/hertz/history 4000 NULL 100
NULL 0.5 0 (k_t = 2/7 k_n, gamma_n = 100 on m_eff sqrt(r_eff delta), no tangential damping,
mu = 0.5), gravity 1, for 25 time units. LAMMPS's fix pour drops batches (224 disks, 40% of
the slab's area at the largest diameter) as the slab clears, the last by t = 12; here the 1000
are inserted at the equivalent steady rate. Statistical comparison of the count, kinetic energies, and bed height against
log.pour.2d.lammps (shipped with LAMMPS). Usage: run.py [-n ranks] [dem-opt]"""
import csv, math, os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[1:]
ranks = 8
if args[:1] == ["-n"]:
    ranks = int(args[1])
    args = args[2:]
exe = args[0] if args else os.path.join(here, "../../../dem-opt")

N = 1000
k_n, gamma_n, mu = 4000.0, 100.0, 0.5
k_t = 2.0 / 7.0 * k_n
# LAMMPS sizes its batches with the largest diameter, 224 disks, and drops them when the slab
# has cleared and has room: its log shows 224, 448, 669, 886, 1000 at t = 2, 4, 8, 10, 12
t_pour = 12.0
rate = N / t_pour
with open(os.path.join(here, "pour_2d.i"), "w") as f:
    f.write(f"""# LAMMPS examples/pour/in.pour.2d in the module; generated by run.py. The Hertz model with
# E* = 3000 (nu = 0, E = 6000) gives k_n = 4/3 E* = 4000 and tangential_stiffness sets 8 G* =
# k_t = 2/7 k_n directly
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 20
    ny = 10
    xmax = 100
    ymax = 50
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '50 32 0'
    radius = 0.5
    density = 1
    disk_mass = true
    gravity = '0 -1 0'
    contact_model = hertz
    youngs_modulus = 6000
    poissons_ratio = 0
    tangential_stiffness = {k_t:.17g}
    normal_damping = {gamma_n}
    tangential_damping = 0
    friction = {mu}
    wall_friction = 0
    rescale_histories = false
    wall_points = '0 0 0
                   100 0 0
                   0 0 0'
    wall_normals = '1 0 0
                    -1 0 0
                    0 1 0'
    insertion_box = '1 30 0
                     99 34.5 0'
    insertion_rate = {rate:.17g}
    insertion_radius_range = '0.25 0.5'
    insertion_end_time = {t_pour + 0.05:.17g}
    insertion_seed = 4767548
    skin = 0.2
    substeps = 100
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [num]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_particles
  []
  [ke]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = kinetic_energy
  []
  [erot]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = rotational_kinetic_energy
  []
  [height]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_y
  []
[]
[Executioner]
  type = Transient
  dt = 0.1
  num_steps = 250
[]
[Outputs]
  csv = true
[]
""")
cmd = ["mpiexec", "-n", str(ranks), exe, "-i", "pour_2d.i"] if ranks > 1 else [exe, "-i", "pour_2d.i"]
out = subprocess.run(cmd, cwd=here, capture_output=True, text=True)
if out.returncode:
    print(out.stdout[-3000:], out.stderr[-2000:])
    sys.exit(1)
lammps = []
for line in open(os.path.join(here, "log.pour.2d.lammps")):
    p = line.split()
    if len(p) == 5 and p[0].isdigit() and all(c in "0123456789.e-+" for c in p[2]):
        lammps.append((int(p[0]) / 1000, int(p[1]), float(p[2]), float(p[3])))
ours = [(float(q["time"]), int(float(q["num"])), float(q["ke"]), float(q["erot"]), float(q["height"]))
        for q in csv.DictReader(open(os.path.join(here, "pour_2d_out.csv")))]
print(f"{'t':>5} {'N LAMMPS':>9} {'N MOOSE':>8} {'KE LAMMPS':>11} {'KE MOOSE':>11} {'Erot LAMMPS':>12} {'Erot MOOSE':>11} {'top MOOSE':>10}")
for t in (2, 4, 6, 8, 10, 15, 20, 25):
    l = next(q for q in lammps if abs(q[0] - t) < 1e-6)
    m = next(q for q in ours if abs(q[0] - t) < 1e-6)
    print(f"{t:5.0f} {l[1]:9d} {m[1]:8d} {l[2]:11.2f} {m[2]:11.2f} {l[3]:12.3f} {m[3]:11.3f} {m[4]:10.2f}")
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(5.5, 3.8))
    ax.plot([q[0] for q in lammps], [q[2] for q in lammps], "k-", label="LAMMPS (batches)")
    ax.plot([q[0] for q in ours], [q[2] for q in ours], "r--", label="MOOSE (steady rate)")
    ax.set_xlabel("time"); ax.set_ylabel("kinetic energy"); ax.set_yscale("log")
    ax.grid(alpha=0.3); ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(here, "pour_2d.png"), dpi=130)
    print("plot: pour_2d.png")
except ImportError:
    pass
