#!/usr/bin/env python3
"""Generate polydisperse.i and its gold: random particles with radii spanning a 50:1 ratio, and
the number of neighbor pairs from a brute-force O(N^2) search (plan case V6)."""
import math, os, random

here = os.path.dirname(os.path.abspath(__file__))
random.seed(7)
n = 300
skin = 0.005
r_min, r_max = 0.002, 0.1
pts = [(random.uniform(0.02, 0.98), random.uniform(0.02, 0.98)) for _ in range(n)]
# Log-uniform radii so small and large particles are equally represented
radii = [math.exp(random.uniform(math.log(r_min), math.log(r_max))) for _ in range(n)]

pairs = sum(1 for i in range(n) for j in range(i + 1, n)
            if math.dist(pts[i], pts[j]) < radii[i] + radii[j] + skin)

positions = "\n                         ".join(f"{x:.6f} {y:.6f} 0" for x, y in pts)
radii_str = "\n                     ".join(f"{r:.6g}" for r in radii)
with open(os.path.join(here, "polydisperse.i"), "w") as f:
    f.write(f"""# V6: the uniform-grid neighbor list must equal a brute-force pair search for random particles
# whose radii span a 50:1 ratio. Generated by generate.py; verify_neighbor_list checks the set of
# pairs on every build and the gold pair count comes from the same brute-force search in Python.
# The particles drift together so rebuilds are triggered but the pair set stays the same.

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 10
    ny = 10
  []
[]

[Problem]
  solve = false
[]

[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{positions}'
    initial_radii = '{radii_str}'
    radius = 0.01
    density = 1000
    initial_velocity = '0.05 0.02 0'
    skin = {skin}
    substeps = 4
    verify = true
    verify_neighbor_list = true
    execute_on = TIMESTEP_END
  []
[]

[Postprocessors]
  [num_neighbor_pairs]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_neighbor_pairs
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [num_neighbor_list_builds]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_neighbor_list_builds
    execute_on = 'INITIAL TIMESTEP_END'
  []
[]

[Executioner]
  type = Transient
  dt = 0.05
  num_steps = 3
[]

[Outputs]
  csv = true
[]
""")

# The cloud drifts 0.05 * 0.05 / 4 = 6.25e-4 per substep; with skin / 2 = 2.5e-3 the list is
# rebuilt every 4th substep after the initial build: 1 at t = 0, then one per step
with open(os.path.join(here, "gold", "polydisperse_out.csv"), "w") as f:
    f.write("time,num_neighbor_list_builds,num_neighbor_pairs\n")
    for step in range(4):
        f.write(f"{step * 0.05:g},{1 + step},{pairs}\n")
print(f"{n} particles, {pairs} pairs")
