#!/usr/bin/env python3
"""LAMMPS examples/granregion/in.granregion.box (in.granregion.box here, run with LAMMPS for
log.granregion.box.lammps): 100 unit spheres poured into a 12-unit cubic container of six
planar walls (gran/hooke 4000 NULL 100 NULL 0.5 1: k_n = 4000, a tangential dashpot gamma_t =
50 on m_eff without a spring, mu = 0.5, LJ units, gravity 1), then five stages of 25 time units:
the container at rest, turning twice about z at 0.503 rad per unit time, at rest, turning twice
about (1, 1, 1), at rest. The module's analytic walls rotate rigidly (wall_angular_velocity)
and each stage restarts from the previous one's checkpoint. Statistical comparison of the
kinetic energies against the LAMMPS log. Usage: run.py [-n ranks] [dem-opt]"""
import csv, math, os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[1:]
ranks = 4
if args[:1] == ["-n"]:
    ranks = int(args[1])
    args = args[2:]
exe = args[0] if args else os.path.join(here, "../../../dem-opt")
omega = 4 * math.pi / (5000 * 0.005)
stages = [("stage1", None, "0 0 0"), ("stage2", "stage1", f"0 0 {omega:.17g}"), ("stage3", "stage2", "0 0 0"),
          ("stage4", "stage3", f"{omega / math.sqrt(3):.17g} {omega / math.sqrt(3):.17g} {omega / math.sqrt(3):.17g}"),
          ("stage5", "stage4", "0 0 0")]
for name, prev, rotation in stages:
    with open(os.path.join(here, name + ".i"), "w") as f:
        f.write(f"""# LAMMPS examples/granregion/in.granregion.box, {name}; generated by run.py
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 11
    ny = 11
    nz = 11
    xmin = -11
    xmax = 11
    ymin = -11
    ymax = 11
    zmin = -11
    zmax = 11
  []
[]
[Problem]
  solve = false
{"  restart_file_base = " + prev + "_out_cp/LATEST" + chr(10) if prev else ""}[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '0 0 0'
    radius = 0.5
    density = 1
    gravity = '0 0 -1'
    normal_stiffness = 4000
    normal_damping = 100
    tangential_stiffness = 0
    tangential_damping = 50
    mass_scaled_damping = true
    friction = 0.5
    wall_points = '-6 0 0
                   6 0 0
                   0 -6 0
                   0 6 0
                   0 0 -6
                   0 0 6'
    wall_normals = '1 0 0
                    -1 0 0
                    0 1 0
                    0 -1 0
                    0 0 1
                    0 0 -1'
    wall_angular_velocity = '{rotation}'
{"    insertion_box = '-2 -2 -2" + chr(10) + "                     2 2 2'" + chr(10) + "    insertion_rate = 10" + chr(10) + "    insertion_end_time = 9.95" + chr(10) + "    insertion_seed = 4767548" + chr(10) if not prev else ""}    skin = 0.15
    substeps = 20
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [num]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_particles
  []
  [ke]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = kinetic_energy
  []
  [erot]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = rotational_kinetic_energy
  []
[]
[Executioner]
  type = Transient
  dt = 0.1
  num_steps = 250
[]
[Outputs]
  csv = true
  checkpoint = true
[]
""")
    cmd = ["mpiexec", "-n", str(ranks), exe, "-i", name + ".i"] if ranks > 1 else [exe, "-i", name + ".i"]
    out = subprocess.run(cmd, cwd=here, capture_output=True, text=True)
    if out.returncode:
        print(out.stdout[-3000:], out.stderr[-2000:])
        sys.exit(1)
lammps = []
for line in open(os.path.join(here, "log.granregion.box.lammps")):
    p = line.split()
    if len(p) == 4 and p[0].isdigit() and p[1].isdigit():
        lammps.append((int(p[0]) * 0.005, int(p[1]), float(p[2]), float(p[3])))
ours = []
for k, (name, _, _) in enumerate(stages):
    for q in csv.DictReader(open(os.path.join(here, name + "_out.csv"))):
        if float(q["time"]) > 25 * k + 1e-9 or k == 0:
            ours.append((float(q["time"]), int(float(q["num"])), float(q["ke"]), float(q["erot"])))
print(f"{'t':>6} {'stage':>6} {'N':>4} {'KE LAMMPS':>10} {'KE MOOSE':>10} {'Erot LAMMPS':>12} {'Erot MOOSE':>11}")
for t in (5, 12.5, 25, 37.5, 50, 62.5, 75, 87.5, 100, 112.5, 125):
    l = [q for q in lammps if abs(q[0] - t) < 1e-6][-1]
    m = [q for q in ours if abs(q[0] - t) < 1e-6][-1]
    print(f"{t:6.1f} {int((t - 1e-9) // 25) + 1:6d} {m[1]:4d} {l[2]:10.2f} {m[2]:10.2f} {l[3]:12.2f} {m[3]:11.2f}")
# Mean energies over the two turning stages, where the bed is carried around by the walls
for lo, hi, label in ((30, 50, "turning about z"), (80, 100, "turning about (1,1,1)")):
    lm = [q[2] for q in lammps if lo <= q[0] <= hi]
    om = [q[2] for q in ours if lo <= q[0] <= hi]
    print(f"{label}: mean KE over t = {lo}-{hi}: LAMMPS {sum(lm) / len(lm):.1f}, MOOSE {sum(om) / len(om):.1f}")
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(6.5, 3.8))
    ax.plot([q[0] for q in lammps], [q[2] for q in lammps], "k-", label="LAMMPS")
    ax.plot([q[0] for q in ours], [q[2] for q in ours], "r--", label="MOOSE")
    ax.set_xlabel("time"); ax.set_ylabel("kinetic energy"); ax.set_yscale("log")
    ax.grid(alpha=0.3); ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(here, "granregion_box.png"), dpi=130)
    print("plot: granregion_box.png")
except ImportError:
    pass
