#!/usr/bin/env python3
"""Silo discharge in 2D (Beverloo et al. 1961; 2D monolayer form as in Janda et al. 2012): a flat-
bottomed silo of width W filled with beads of diameter d drains through a floor orifice of width D
at a rate Q that (i) is independent of the fill height once the bed is taller than ~W (Janssen) and
(ii) scales as Q = C rho_b sqrt(g) (D - k d)^(3/2) in 2D. Generates one input per orifice width (the
floor is the 'bottom' sideset with the orifice cut out by ParsedGenerateSideset, so beads that fall
through leave the mesh and count as exited), runs them, fits the exited count against time over the
steady window, and plots Q^(2/3) against D, which Beverloo's law makes a straight line with
x-intercept k d. Usage: run.py [dem-opt] [orifice widths in diameters...]"""
import csv, math, os, subprocess, sys, random

here = os.path.dirname(os.path.abspath(__file__))
exe = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "../../dem-opt")
widths = [float(a) for a in sys.argv[2:]] or [4.0, 5.0, 6.0, 8.0, 10.0]

r = 0.003                        # 6 mm beads
d = 2 * r
W = 30 * d                       # silo width, 30 diameters: the widest orifice is a third of it
H = 48 * d                       # fill height, 1.6 W: the discharge starts in the Janssen regime
dx = r                           # element width: the orifice edges land on element boundaries
mu, mu_r = 0.5, 0.1
T = 4.0                          # run time; the widest orifice drains most of the bed by then
random.seed(1)


def fill():
    """Hexagonal packing of the silo interior up to height H"""
    sx, sy = d * 1.02, d * 1.02 * math.sqrt(3) / 2
    pts = []
    row = 0
    y = r * 1.05
    while y < H:
        x = -W / 2 + r * 1.05 + (sx / 2 if row % 2 else 0)
        while x < W / 2 - r * 1.05:
            pts.append((x + random.uniform(-1, 1) * 0.01 * r, y, 0))
            x += sx
        y += sy
        row += 1
    return pts


pts = fill()
Hmesh = H + 0.03
results = []
for D in widths:
    base = f"silo_D{D:g}"
    with open(os.path.join(here, base + ".i"), "w") as f:
        f.write(f"""# Silo discharge, orifice {D:g} diameters: {len(pts)} beads, generated by run.py
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = {int(round(W / dx))}
    ny = {int(round(Hmesh / d))}
    xmin = {-W / 2:.4f}
    xmax = {W / 2:.4f}
    ymax = {Hmesh:.4f}
  []
  [floor]
    type = ParsedGenerateSideset
    input = gen
    combinatorial_geometry = 'abs(x) > {D * d / 2:.6f}'
    included_boundaries = bottom
    new_sideset_name = floor
    replace = true
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{x:.6f} {y:.6f} {z}" for x, y, z in pts)}'
    radius = {r}
    density = 2500
    gravity = '0 -9.81 0'
    normal_stiffness = 1e5
    normal_damping = 2
    tangential_stiffness = 1e5
    tangential_damping = 2
    friction = {mu}
    rolling_stiffness = 1e5
    rolling_damping = 2
    rolling_friction = {mu_r}
    wall_boundaries = 'left right floor'
    skin = 0.0006
    substeps = 400
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [exited]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_exited
  []
  [height]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_y
  []
[]
[Executioner]
  type = Transient
  dt = 0.01
  num_steps = {int(round(T / 0.01))}
[]
[Outputs]
  csv = true
[]
""")
    run = subprocess.run([exe, "-i", base + ".i"], cwd=here, capture_output=True, text=True)
    if run.returncode:
        print(run.stdout[-2000:], run.stderr[-2000:])
        sys.exit(1)
    rows = list(csv.DictReader(open(os.path.join(here, base + "_out.csv"))))
    t = [float(q["time"]) for q in rows]
    n = [float(q["exited"]) for q in rows]
    h = [float(q["height"]) for q in rows]
    # Steady window: after the lattice has settled onto the floor (0.3 s) and while the free
    # surface is still above one silo width, where Janssen's saturation holds the floor stress
    win = [i for i in range(len(t)) if t[i] >= 0.3 and h[i] >= W]
    tw, nw = [t[i] for i in win], [n[i] for i in win]
    tm, nm = sum(tw) / len(tw), sum(nw) / len(nw)
    Q = sum((a - tm) * (b - nm) for a, b in zip(tw, nw)) / sum((a - tm) ** 2 for a in tw)
    # Residual of the linear fit as a fraction of the exited count over the window, the
    # measure of how steady (fill-height independent) the discharge was
    resid = math.sqrt(sum((b - nm - Q * (a - tm)) ** 2 for a, b in zip(tw, nw)) / len(tw)) / max(nw[-1] - nw[0], 1)
    results.append((D, Q, resid, n[-1]))
    print(f"D = {D:g} d: Q = {Q:.1f} beads/s over t = [{tw[0]:.2f}, {tw[-1]:.2f}] s "
          f"(linear fit residual {100 * resid:.1f}% of the discharge), {int(n[-1])} of {len(pts)} exited by t = {t[-1]:.2f} s")
if len(results) < 3:
    sys.exit(0)

# Beverloo: Q^(2/3) = C^(2/3) (D - k d) is linear in D with x-intercept k d
Ds = [q[0] * d for q in results]
Qs = [q[1] ** (2 / 3) for q in results]
Dm, Qm = sum(Ds) / len(Ds), sum(Qs) / len(Qs)
slope = sum((a - Dm) * (b - Qm) for a, b in zip(Ds, Qs)) / sum((a - Dm) ** 2 for a in Ds)
k = (Dm - Qm / slope) / d
# Free-exponent fit Q = A (D - k d)^n for comparison with n = 3/2
lx = [math.log(a - k * d) for a in Ds]
ly = [math.log(q[1]) for q in results]
lxm, lym = sum(lx) / len(lx), sum(ly) / len(ly)
nexp = sum((a - lxm) * (b - lym) for a, b in zip(lx, ly)) / sum((a - lxm) ** 2 for a in lx)
print(f"Beverloo fit: k = {k:.2f} (2D disks: 1-2), exponent with that k: {nexp:.2f} (Beverloo 2D: 1.5)")

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(5.5, 4.2))
    ax.plot([q[0] for q in results], Qs, "o", label="DEM")
    xx = [k, max(widths)]
    ax.plot(xx, [slope * (x * d - k * d) for x in xx], "k--", label=f"Beverloo: Q^(2/3) ~ (D - {k:.2f} d)")
    ax.set_xlabel("orifice width D / d")
    ax.set_ylabel("Q^(2/3)  [(beads/s)^(2/3)]")
    ax.grid(alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(here, "silo_discharge.png"), dpi=130)
    print("plot: silo_discharge.png")
except ImportError:
    pass
