#!/usr/bin/env python3
"""Axisymmetric granular column collapse (Lube, Huppert, Sparks & Hallworth 2004, J. Fluid Mech.
508; Lajeunesse, Mangeney-Castelnau & Vilotte 2004, Phys. Fluids 16): a cylinder of grains of
radius R0 and height H0 = a R0 released on a flat floor spreads to a deposit of radius R_inf and
height H_inf with

    (R_inf - R0) / R0 = 1.24 a (a < 1.7),  1.6 a^(1/2) (a > 1.7)         Lube et al.
    (R_inf - R0) / R0 = 1.0 a  (a < 0.74), 2.0 a^(1/2) (a > 0.74)        Lajeunesse et al.
    H_inf / R0 = a (small a),  0.88 a^(1/6) (large a; the two meet at a = 0.85)   Lube et al.

independent of the grain material. The bed is poured (random rain into a cylinder, no lattice),
settled, and sliced at H0 for each aspect ratio; the columns are released on a box mesh whose
bottom sideset is the floor. The deposit edge is the outermost annulus of width d still covered
by at least 30% of a monolayer; the farthest grain is reported alongside.
Usage: run.py [-n ranks] [dem-opt] [aspect ratios...]"""
import csv, glob, math, os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[1:]
ranks = 8
if args[:1] == ["-n"]:
    ranks = int(args[1])
    args = args[2:]
exe = args[0] if args and not args[0].replace(".", "").isdigit() else os.path.join(here, "../../dem-opt")
aspects = [float(a) for a in args if a.replace(".", "").isdigit()] or [0.5, 1.0, 2.0, 3.0]

d = 0.006                        # 6 mm beads
r = d / 2
R0 = 12 * d                      # column radius
rho = 2500
g = 9.81
mu, mu_r = 0.5, 0.1
m = rho * 4 / 3 * math.pi * r**3
# Linear spring: the beads at the bottom of a 36 d column overlap by 36 m g / k = 0.6% of r;
# damping gives a restitution of about 0.45 (damping ratio 0.25); the substep is a 26th of the
# contact time pi / sqrt(k / m_eff) with m_eff = m / 2
k = 5e3
c = 0.25 * 2 * math.sqrt(k * m / 2)
substeps = 500
Hfill = (max(aspects) * 12 + 8) * d    # poured bed: the tallest column plus the heap's slope
Hcyl = Hfill + 12 * d
N = int(0.6 * math.pi * R0**2 * Hfill / (4 / 3 * math.pi * r**3))   # beads at 60% packing
rate = 15000                     # beads per second poured
t_pour = N / rate
t_fill = t_pour + 0.8            # then settle


def run(base):
    cmd = ["mpiexec", "-n", str(ranks), exe, "-i", base + ".i"] if ranks > 1 else [exe, "-i", base + ".i"]
    out = subprocess.run(cmd, cwd=here, capture_output=True, text=True)
    if out.returncode:
        print(out.stdout[-3000:], out.stderr[-2000:])
        sys.exit(1)


def cloud(positions, walls, extra=""):
    return f"""[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{x:.6f} {y:.6f} {z:.6f}" for x, y, z in positions)}'
    radius = {r}
    density = {rho}
    gravity = '0 0 -{g}'
    normal_stiffness = {k}
    normal_damping = {c}
    tangential_stiffness = {k}
    tangential_damping = {c}
    friction = {mu}
    rolling_stiffness = {k}
    rolling_damping = {c}
    rolling_friction = {mu_r}
    wall_boundaries = '{walls}'
    skin = {r / 2}
    substeps = {substeps}
    timestep_check = error
    execute_on = TIMESTEP_END
{extra}  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [ke]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = kinetic_energy
  []
  [num]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_particles
  []
  [height]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_z
  []
[]
"""


# 1. Pour the bed into a cylinder of radius R0 from a box inscribed in its top
s = R0 / math.sqrt(2) - 1.1 * r
with open(os.path.join(here, "fill.i"), "w") as f:
    f.write(f"""# Poured bed for the column collapse: {N} beads rained into a cylinder, generated by run.py
[Mesh]
  [disk]
    type = ConcentricCircleMeshGenerator
    num_sectors = 8
    radii = '{R0:.6f}'
    rings = '4'
    has_outer_square = false
    preserve_volumes = true
    smoothing_max_it = 0
  []
  [cylinder]
    type = AdvancedExtruderGenerator
    input = disk
    direction = '0 0 1'
    heights = '{Hcyl:.4f}'
    num_layers = {int(round(Hcyl / (2 * d)))}
    bottom_boundary = 100
    top_boundary = 101
  []
[]
[Problem]
  solve = false
[]
""" + cloud([(0, 0, r * 1.05)], "outer 100", f"""    insertion_box = '{-s:.5f} {-s:.5f} {Hfill + 6 * d:.5f}
                     {s:.5f} {s:.5f} {Hfill + 11 * d:.5f}'
    insertion_rate = {rate}
    insertion_velocity = '0 0 -1'
    insertion_end_time = {t_pour:.4f}
    insertion_seed = 7
""") + f"""[Executioner]
  type = Transient
  dt = 0.01
  num_steps = {int(round(t_fill / 0.01))}
[]
[Outputs]
  [csv]
    type = CSV
    execute_postprocessors_on = TIMESTEP_END
    execute_vector_postprocessors_on = FINAL
  []
  [console]
    type = Console
    execute_postprocessors_on = NONE
  []
[]
""")
if not glob.glob(os.path.join(here, "fill_csv_state_*.csv")):
    print(f"pouring {N} beads ...", flush=True)
    run("fill")
state = sorted(glob.glob(os.path.join(here, "fill_csv_state_*.csv")))[-1]
bed = [(float(q["x"]), float(q["y"]), float(q["z"])) for q in csv.DictReader(open(state))]
bed_ke = max(float(q["vx"])**2 + float(q["vy"])**2 + float(q["vz"])**2 for q in csv.DictReader(open(state)))
zs = sorted(p[2] for p in bed)
print(f"bed: {len(bed)} beads, top at {zs[-1] / d:.1f} d, 95th percentile {zs[int(0.95 * len(zs))] / d:.1f} d, "
      f"max |v| {math.sqrt(bed_ke):.1e} m/s", flush=True)

# 2. Release the columns
results = []
for a in aspects:
    H0 = a * R0
    pts = [p for p in bed if p[2] < H0 - r]
    if zs[int(0.99 * len(zs))] < H0:
        print(f"a = {a:g}: the poured bed is not tall enough ({zs[-1] / d:.1f} d < {H0 / d:.1f} d)")
        continue
    L = R0 * (1 + 2.0 * math.sqrt(max(a, 1)) + 0.5)      # box half-width beyond Lajeunesse's runout
    Hbox = H0 + 0.05
    T = 0.3 + 6 * math.sqrt(H0 / g)                      # Lube: the front stops by 3 sqrt(H0/g); twice that
    base = f"collapse3d_a{a:g}"
    with open(os.path.join(here, base + ".i"), "w") as f:
        f.write(f"""# Axisymmetric column collapse, a = {a:g}: {len(pts)} beads, generated by run.py
[Mesh]
  [box]
    type = GeneratedMeshGenerator
    dim = 3
    nx = {int(2 * L / 0.02) + 1}
    ny = {int(2 * L / 0.02) + 1}
    nz = {int(Hbox / 0.02) + 1}
    xmin = {-L:.4f}
    xmax = {L:.4f}
    ymin = {-L:.4f}
    ymax = {L:.4f}
    zmax = {Hbox:.4f}
  []
[]
[Problem]
  solve = false
[]
""" + cloud(pts, "back") + f"""[Executioner]
  type = Transient
  dt = 0.01
  num_steps = {int(round(T / 0.01))}
[]
[Outputs]
  [csv]
    type = CSV
    execute_postprocessors_on = TIMESTEP_END
    execute_vector_postprocessors_on = FINAL
  []
  [console]
    type = Console
    execute_postprocessors_on = NONE
  []
[]
""")
    run(base)
    final = sorted(glob.glob(os.path.join(here, base + "_csv_state_*.csv")))[-1]
    hist = list(csv.DictReader(open(os.path.join(here, base + "_csv.csv"))))
    ke = [(float(q["time"]), float(q["ke"])) for q in hist]
    ke_max = max(v for _, v in ke)
    t_rest = next((t for t, v in ke if v < 1e-4 * ke_max), None)   # KE within 1e-4 of its peak
    dep = [(float(q["x"]), float(q["y"]), float(q["z"]), float(q["vx"])**2 + float(q["vy"])**2 + float(q["vz"])**2)
           for q in csv.DictReader(open(final))]
    rad = sorted(math.hypot(p[0], p[1]) for p in dep)
    # Deposit edge: outermost annulus of width d holding at least 30% of a monolayer
    nb = int(rad[-1] / d) + 1
    counts = [0] * nb
    for q in rad:
        counts[int(q / d)] += 1
    edge = max(i for i in range(nb) if counts[i] >= 0.3 * (2 * i + 1) * math.pi) * d + d
    Hinf = max(p[2] for p in dep if math.hypot(p[0], p[1]) < 2 * d) + r
    results.append((a, len(pts), (edge - R0) / R0, (rad[-1] - R0) / R0, Hinf / R0))
    lube = 1.24 * a if a < 1.7 else 1.6 * math.sqrt(a)
    lube_h = a if a < 0.85 else 0.88 * a ** (1 / 6)
    print(f"a = {a:g}: {len(pts)} beads, (R_inf - R0)/R0 = {(edge - R0) / R0:.2f} (Lube {lube:.2f}, "
          f"{100 * ((edge - R0) / R0 / lube - 1):+.0f}%; farthest grain {(rad[-1] - R0) / R0:.2f}), "
          f"H_inf/R0 = {Hinf / R0:.2f} (Lube {lube_h:.2f}); KE down to 1e-4 of its peak at t = {t_rest} s "
          f"(Lube t_inf = {3 * math.sqrt(H0 / g):.2f} s), max |v| {math.sqrt(max(p[3] for p in dep)):.1e} m/s at t = {T:.2f} s", flush=True)

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, axs = plt.subplots(1, 2, figsize=(9, 4))
    aa = [0.3 * 1.1**i for i in range(30)]
    axs[0].loglog([q[0] for q in results], [q[2] for q in results], "o", label="DEM deposit edge")
    axs[0].loglog([q[0] for q in results], [q[3] for q in results], "x", color="gray", label="DEM farthest grain")
    axs[0].loglog(aa, [1.24 * x if x < 1.7 else 1.6 * math.sqrt(x) for x in aa], "k--", label="Lube et al. 2004")
    axs[0].loglog(aa, [1.0 * x if x < 0.74 else 2.0 * math.sqrt(x) for x in aa], "k:", label="Lajeunesse et al. 2004")
    axs[0].set_xlabel("a = H0 / R0")
    axs[0].set_ylabel("(R_inf - R0) / R0")
    axs[1].loglog([q[0] for q in results], [q[4] for q in results], "o", label="DEM")
    axs[1].loglog(aa, [x if x < 0.85 else 0.88 * x ** (1 / 6) for x in aa], "k--", label="Lube et al. 2004")
    axs[1].set_xlabel("a = H0 / R0")
    axs[1].set_ylabel("H_inf / R0")
    for ax in axs:
        ax.grid(alpha=0.3, which="both")
        ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(os.path.join(here, "column_collapse_3d.png"), dpi=130)
    print("plot: column_collapse_3d.png")
except ImportError:
    pass
