#!/usr/bin/env python3
"""Cross-code check against LAMMPS (22 Jul 2025): the inputs under lammps/ were run with
    lmp -in in.<case>
and their dumps (positions, velocities, and spins to 17 digits) are the references. This script
writes the MOOSE inputs from the step-0 frame of each dump and the gold CSVs from the later
frames, in the layout of KokkosParticleState. Both codes integrate with velocity Verlet and the
same contact conventions (undeformed radii at the contact point, torque arm r_i), so the
trajectories agree to roundoff (5e-14 in position) as long as the models coincide:
LAMMPS gran/hooke/history <-> LinearSpringDashpot with normal_damping = m_eff gamma_n,
rescale_histories = false (the gran/* styles only project a rotated spring),
tangential_damping = m_eff gamma_t (all masses 1, so m_eff = 1/2 between particles and 1
against the wall), friction = xmu, and fix wall/gran hooke/history <-> an analytic wall.
Two conventions differ and are kept out of the reference windows: LAMMPS caps the tangential
force at mu |F_n| where this module uses mu max(F_n, 0), which matters only when the dashpot
makes the normal force attractive (fast separation); and LAMMPS's setup-step force evaluation
does not advance the histories, so a contact whose dashpot alone exceeds the Coulomb limit at
step 0 gets no tangential force on that step (the cases therefore start from rest or without
friction)."""
import math, os

here = os.path.dirname(os.path.abspath(__file__))


def read_dump(path):
    frames = {}
    lines = open(path).read().split("\n")
    i = 0
    while i < len(lines):
        if lines[i].startswith("ITEM: TIMESTEP"):
            step = int(lines[i + 1])
            n = int(lines[i + 3])
            box = [tuple(map(float, lines[i + 5 + k].split())) for k in range(3)]
            cols = lines[i + 8].split()[2:]
            rows = [dict(zip(cols, map(float, lines[i + 9 + k].split()))) for k in range(n)]
            frames[step] = (box, {int(r["id"]): r for r in rows})
            i += 9 + n
        else:
            i += 1
    return frames


def gold(frames, step, name, periodic):
    """Gold CSV in the KokkosParticleState layout (columns alphabetical, rows by gid); LAMMPS
    wraps positions only when it reneighbors, the module at every step end"""
    box, p = frames[step]
    with open(os.path.join(here, "gold", name), "w") as f:
        f.write("gid,vx,vy,vz,wx,wy,wz,x,y,z\n")
        for i in sorted(p):
            q = dict(p[i])
            if periodic:
                for c, (lo, hi) in zip("xyz", box):
                    q[c] = lo + (q[c] - lo) % (hi - lo)
            f.write(",".join([str(i - 1)] + [f"{q[c]:.17g}" for c in ("vx", "vy", "vz", "omegax", "omegay", "omegaz", "x", "y", "z")]) + "\n")


r = 0.625
rho = 1 / (4 / 3 * math.pi * r**3)     # unit mass

# The 32-sphere unittest configuration of LAMMPS (jittered fcc, fully periodic), frictionless
# and with friction from rest (mu = 0.02: most contacts slide at the Coulomb limit)
for case, mu in (("hooke_history_nofric", 0), ("hooke_history_rest", 0.02)):
    frames = read_dump(os.path.join(here, "lammps", "dump." + case))
    box, p0 = frames[0]
    L = box[0][1]
    ids = sorted(p0)
    with open(os.path.join(here, case + ".i"), "w") as f:
        f.write(f"""# LAMMPS pair gran/hooke/history 1000 500 50 50 {mu} 1 on the 32-sphere configuration of its
# granular unit tests (lammps/in.{case}); generated by generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 4
    ny = 4
    nz = 4
    xmax = {L:.17g}
    ymax = {L:.17g}
    zmax = {L:.17g}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{p0[i]['x']:.17g} {p0[i]['y']:.17g} {p0[i]['z']:.17g}" for i in ids)}'
    initial_velocities = '{chr(10).join(f"{p0[i]['vx']:.17g} {p0[i]['vy']:.17g} {p0[i]['vz']:.17g}" for i in ids)}'
    radius = {r}
    density = {rho:.17g}
    normal_stiffness = 1000
    normal_damping = 25
    tangential_stiffness = 500
    tangential_damping = 25
    friction = {mu}
    rescale_histories = false
    periodic = 'x y z'
    skin = 0.3
    substeps = 50
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.05
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
    gold(frames, 50, case + "_out_state_0001.csv", True)
    gold(frames, 100, case + "_out_state_0002.csv", True)

# gran/hooke: the tangential dashpot alone under the Coulomb cap, no spring
frames = read_dump(os.path.join(here, "lammps", "dump.hooke_nohistory"))
box, p0 = frames[0]
L = box[0][1]
ids = sorted(p0)
with open(os.path.join(here, "hooke_nohistory.i"), "w") as f:
    f.write(f"""# LAMMPS pair gran/hooke 1000 NULL 50 50 0.4 1 (tangential dashpot without a spring) on the
# compressed 32-sphere lattice at low speed (lammps/in.hooke_nohistory); generated by
# generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 4
    ny = 4
    nz = 4
    xmax = {L:.17g}
    ymax = {L:.17g}
    zmax = {L:.17g}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{p0[i]['x']:.17g} {p0[i]['y']:.17g} {p0[i]['z']:.17g}" for i in ids)}'
    initial_velocities = '{chr(10).join(f"{p0[i]['vx']:.17g} {p0[i]['vy']:.17g} {p0[i]['vz']:.17g}" for i in ids)}'
    radius = {r}
    density = {rho:.17g}
    normal_stiffness = 1000
    normal_damping = 25
    tangential_stiffness = 0
    tangential_damping = 25
    friction = 0.4
    periodic = 'x y z'
    skin = 0.3
    substeps = 50
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.05
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
gold(frames, 50, "hooke_nohistory_out_state_0001.csv", True)
gold(frames, 100, "hooke_nohistory_out_state_0002.csv", True)

# gran/hertz/history with limit_damping from rest: the Hertz model with E = 4000/3 and nu = 1/3
# gives E* = 750 (k_n = 4/3 E* = 1000) and 8 G* = 1200 = k_t; normal_damping and
# tangential_damping are LAMMPS's gamma_n and gamma_t on m_eff sqrt(r_eff overlap)
frames = read_dump(os.path.join(here, "lammps", "dump.hertz_history"))
box, p0 = frames[0]
L = box[0][1]
ids = sorted(p0)
with open(os.path.join(here, "hertz_history.i"), "w") as f:
    f.write(f"""# LAMMPS pair gran/hertz/history 1000 1200 50 30 0.5 1 limit_damping on the compressed
# 32-sphere lattice from rest (lammps/in.hertz_history); generated by generate.py, gold from
# the dump. E = 4000/3 and nu = 1/3 give k_n = 4/3 E* = 1000 and k_t = 8 G* = 1200
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 4
    ny = 4
    nz = 4
    xmax = {L:.17g}
    ymax = {L:.17g}
    zmax = {L:.17g}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{p0[i]['x']:.17g} {p0[i]['y']:.17g} {p0[i]['z']:.17g}" for i in ids)}'
    radius = {r}
    density = {rho:.17g}
    contact_model = hertz
    youngs_modulus = {4000 / 3:.17g}
    poissons_ratio = {1 / 3:.17g}
    normal_damping = 50
    tangential_damping = 30
    limit_damping = true
    friction = 0.5
    rescale_histories = false
    periodic = 'x y z'
    skin = 0.3
    substeps = 50
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.05
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
gold(frames, 50, "hertz_history_out_state_0001.csv", True)
gold(frames, 100, "hertz_history_out_state_0002.csv", True)

# pair granular hertz/material + mindlin + rolling sds + coeff_restitution damping +
# limit_damping from rest: the module's Hertz-Mindlin-EPSD model with LAMMPS pair granular's
# conventions (springs rescaled on rotation, torque arm at the contact plane)
frames = read_dump(os.path.join(here, "lammps", "dump.granular_hertz"))
box, p0 = frames[0]
L = box[0][1]
ids = sorted(p0)
with open(os.path.join(here, "granular_hertz.i"), "w") as f:
    f.write(f"""# LAMMPS pair granular hertz/material 4000/3 0.8 1/3, mindlin NULL sqrt(0.8) 0.5, rolling sds
# 500 50 0.1, damping coeff_restitution, limit_damping, on the compressed 32-sphere lattice from
# rest (lammps/in.granular_hertz); generated by generate.py, gold from the dump. xt = sqrt(0.8)
# = sqrt(S_t / S_n) makes LAMMPS's tangential dashpot the Tsuji form on S_t used here
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 4
    ny = 4
    nz = 4
    xmax = {L:.17g}
    ymax = {L:.17g}
    zmax = {L:.17g}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{p0[i]['x']:.17g} {p0[i]['y']:.17g} {p0[i]['z']:.17g}" for i in ids)}'
    radius = {r}
    density = {rho:.17g}
    contact_model = hertz
    youngs_modulus = {4000 / 3:.17g}
    poissons_ratio = {1 / 3:.17g}
    restitution = 0.8
    limit_damping = true
    friction = 0.5
    rolling_stiffness = 500
    rolling_damping = 50
    rolling_friction = 0.1
    deformed_torque_arm = true
    periodic = 'x y z'
    skin = 0.3
    substeps = 50
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.05
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
gold(frames, 50, "granular_hertz_out_state_0001.csv", True)
gold(frames, 100, "granular_hertz_out_state_0002.csv", True)

# pair granular hooke + linear_history + velocity damping + limit_damping from rest: the
# linear model with pair granular's conventions
frames = read_dump(os.path.join(here, "lammps", "dump.granular_hooke"))
box, p0 = frames[0]
L = box[0][1]
ids = sorted(p0)
with open(os.path.join(here, "granular_hooke.i"), "w") as f:
    f.write(f"""# LAMMPS pair granular hooke 1000 25, linear_history 500 1 0.02, damping velocity,
# limit_damping, on the compressed 32-sphere lattice from rest (lammps/in.granular_hooke);
# generated by generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 4
    ny = 4
    nz = 4
    xmax = {L:.17g}
    ymax = {L:.17g}
    zmax = {L:.17g}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{p0[i]['x']:.17g} {p0[i]['y']:.17g} {p0[i]['z']:.17g}" for i in ids)}'
    radius = {r}
    density = {rho:.17g}
    normal_stiffness = 1000
    normal_damping = 25
    tangential_stiffness = 500
    tangential_damping = 25
    limit_damping = true
    friction = 0.02
    deformed_torque_arm = true
    periodic = 'x y z'
    skin = 0.3
    substeps = 50
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.05
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
gold(frames, 50, "granular_hooke_out_state_0001.csv", True)
gold(frames, 100, "granular_hooke_out_state_0002.csv", True)

# Two shearing zplane walls (fix wall/gran ... shear x 0.5, the setting of LAMMPS's
# fix-timestep-wall_gran unit test) on a lattice of thermal spheres, periodic in x and y
frames = read_dump(os.path.join(here, "lammps", "dump.wall_gran_shear"))
box, p0 = frames[0]
L = box[0][1]
ids = sorted(p0)
rw = 0.5
with open(os.path.join(here, "wall_gran_shear.i"), "w") as f:
    f.write(f"""# LAMMPS fix wall/gran hooke/history 1000 2/7 1000 1e-9 1.25 0.5 1 zplane -0.6 3.96 shear x 0.5
# with pair gran/hooke/history 1000 2/7 1000 1e-9 2.5 0.5 1 (lammps/in.wall_gran_shear): 32
# thermal spheres between two floors moving at 0.5 in x; generated by generate.py, gold from
# the dump. The 1e-9 normal damping (zero makes LAMMPS produce NaN) times m_eff = 1/2 is kept
# for the pairs; the walls get the same value where LAMMPS uses twice it, a force 1e-10 of the
# spring's
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 4
    ny = 4
    nz = 5
    xmax = {L:.17g}
    ymax = {L:.17g}
    zmin = {box[2][0]:.17g}
    zmax = {box[2][1]:.17g}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{p0[i]['x']:.17g} {p0[i]['y']:.17g} {p0[i]['z']:.17g}" for i in ids)}'
    initial_velocities = '{chr(10).join(f"{p0[i]['vx']:.17g} {p0[i]['vy']:.17g} {p0[i]['vz']:.17g}" for i in ids)}'
    radius = {rw}
    density = {1 / (4 / 3 * math.pi * rw**3):.17g}
    normal_stiffness = 1000
    normal_damping = 5e-10
    tangential_stiffness = {2000 / 7:.17g}
    tangential_damping = 1.25
    friction = 0.5
    wall_friction = 0.5
    rescale_histories = false
    wall_points = '0 0 -0.6
                   0 0 3.96'
    wall_normals = '0 0 1
                    0 0 -1'
    wall_velocities = '0.5 0 0
                       0.5 0 0'
    periodic = 'x y'
    skin = 0.3
    substeps = 50
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.1
  num_steps = 4
[]
[Outputs]
  csv = true
[]
""")
for step in (50, 100, 150, 200):
    gold(frames, step, f"wall_gran_shear_out_state_{step // 50:04d}.csv", True)

# A spinning sphere hitting the floor obliquely (fix wall/gran hooke/history zplane); the
# reference stops at step 50, before the separating phase where the normal force turns
# attractive and the Coulomb cap conventions part
frames = read_dump(os.path.join(here, "lammps", "dump.wall_gran"))
with open(os.path.join(here, "wall_gran.i"), "w") as f:
    f.write(f"""# LAMMPS fix wall/gran hooke/history 1000 500 50 50 0.4 1 zplane (lammps/in.wall_gran): a
# spinning sphere hits the floor obliquely; generated by generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 3
    ny = 3
    nz = 2
    xmin = -3
    xmax = 3
    ymin = -3
    ymax = 3
    zmin = -1
    zmax = 3
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '0 0 0.63'
    initial_velocities = '1.0 0.3 -2.0'
    initial_angular_velocity = '0.0 4.0 1.0'
    radius = {r}
    density = {rho:.17g}
    normal_stiffness = 1000
    normal_damping = 50
    tangential_stiffness = 500
    tangential_damping = 50
    friction = 0.4
    rescale_histories = false
    wall_points = '0 0 0'
    wall_normals = '0 0 1'
    skin = 0.3
    substeps = 25
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.025
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
gold(frames, 25, "wall_gran_out_state_0001.csv", False)
gold(frames, 50, "wall_gran_out_state_0002.csv", False)
