#!/usr/bin/env python3
"""Cross-code check against LAMMPS (22 Jul 2025): the inputs under lammps/ were run with
    lmp -in in.<case>
and their dumps (positions, velocities, and spins to 17 digits) are the references. This script
writes the MOOSE inputs from the step-0 frame of each dump and the gold CSVs from the later
frames, in the layout of KokkosParticleState. Both codes integrate with velocity Verlet and the
same contact conventions (undeformed radii at the contact point, torque arm r_i), so the
trajectories agree to roundoff (5e-14 in position) as long as the models coincide:
LAMMPS gran/hooke/history <-> LinearSpringDashpot with normal_damping = m_eff gamma_n,
tangential_damping = m_eff gamma_t (all masses 1, so m_eff = 1/2 between particles and 1
against the wall), friction = xmu, and fix wall/gran hooke/history <-> an analytic wall.
Two conventions differ and are kept out of the reference windows: LAMMPS caps the tangential
force at mu |F_n| where this module uses mu max(F_n, 0), which matters only when the dashpot
makes the normal force attractive (fast separation); and LAMMPS's setup-step force evaluation
does not advance the histories, so a contact whose dashpot alone exceeds the Coulomb limit at
step 0 gets no tangential force on that step (the cases therefore start from rest or without
friction)."""
import math, os

here = os.path.dirname(os.path.abspath(__file__))


def read_dump(path):
    frames = {}
    lines = open(path).read().split("\n")
    i = 0
    while i < len(lines):
        if lines[i].startswith("ITEM: TIMESTEP"):
            step = int(lines[i + 1])
            n = int(lines[i + 3])
            box = [tuple(map(float, lines[i + 5 + k].split())) for k in range(3)]
            cols = lines[i + 8].split()[2:]
            rows = [dict(zip(cols, map(float, lines[i + 9 + k].split()))) for k in range(n)]
            frames[step] = (box, {int(r["id"]): r for r in rows})
            i += 9 + n
        else:
            i += 1
    return frames


def gold(frames, step, name, periodic):
    """Gold CSV in the KokkosParticleState layout (columns alphabetical, rows by gid); LAMMPS
    wraps positions only when it reneighbors, the module at every step end"""
    box, p = frames[step]
    with open(os.path.join(here, "gold", name), "w") as f:
        f.write("gid,vx,vy,vz,wx,wy,wz,x,y,z\n")
        for i in sorted(p):
            q = dict(p[i])
            if periodic:
                for c, (lo, hi) in zip("xyz", box):
                    q[c] = lo + (q[c] - lo) % (hi - lo)
            f.write(",".join([str(i - 1)] + [f"{q[c]:.17g}" for c in ("vx", "vy", "vz", "omegax", "omegay", "omegaz", "x", "y", "z")]) + "\n")


r = 0.625
rho = 1 / (4 / 3 * math.pi * r**3)     # unit mass

# The 32-sphere unittest configuration of LAMMPS (jittered fcc, fully periodic), frictionless
# and with friction from rest (mu = 0.02: most contacts slide at the Coulomb limit)
for case, mu in (("hooke_history_nofric", 0), ("hooke_history_rest", 0.02)):
    frames = read_dump(os.path.join(here, "lammps", "dump." + case))
    box, p0 = frames[0]
    L = box[0][1]
    ids = sorted(p0)
    with open(os.path.join(here, case + ".i"), "w") as f:
        f.write(f"""# LAMMPS pair gran/hooke/history 1000 500 50 50 {mu} 1 on the 32-sphere configuration of its
# granular unit tests (lammps/in.{case}); generated by generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 4
    ny = 4
    nz = 4
    xmax = {L:.17g}
    ymax = {L:.17g}
    zmax = {L:.17g}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{p0[i]['x']:.17g} {p0[i]['y']:.17g} {p0[i]['z']:.17g}" for i in ids)}'
    initial_velocities = '{chr(10).join(f"{p0[i]['vx']:.17g} {p0[i]['vy']:.17g} {p0[i]['vz']:.17g}" for i in ids)}'
    radius = {r}
    density = {rho:.17g}
    normal_stiffness = 1000
    normal_damping = 25
    tangential_stiffness = 500
    tangential_damping = 25
    friction = {mu}
    periodic = 'x y z'
    skin = 0.3
    substeps = 50
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.05
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
    gold(frames, 50, case + "_out_state_0001.csv", True)
    gold(frames, 100, case + "_out_state_0002.csv", True)

# A spinning sphere hitting the floor obliquely (fix wall/gran hooke/history zplane); the
# reference stops at step 50, before the separating phase where the normal force turns
# attractive and the Coulomb cap conventions part
frames = read_dump(os.path.join(here, "lammps", "dump.wall_gran"))
with open(os.path.join(here, "wall_gran.i"), "w") as f:
    f.write(f"""# LAMMPS fix wall/gran hooke/history 1000 500 50 50 0.4 1 zplane (lammps/in.wall_gran): a
# spinning sphere hits the floor obliquely; generated by generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 3
    ny = 3
    nz = 2
    xmin = -3
    xmax = 3
    ymin = -3
    ymax = 3
    zmin = -1
    zmax = 3
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '0 0 0.63'
    initial_velocities = '1.0 0.3 -2.0'
    initial_angular_velocity = '0.0 4.0 1.0'
    radius = {r}
    density = {rho:.17g}
    normal_stiffness = 1000
    normal_damping = 50
    tangential_stiffness = 500
    tangential_damping = 50
    friction = 0.4
    wall_points = '0 0 0'
    wall_normals = '0 0 1'
    skin = 0.3
    substeps = 25
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.025
  num_steps = 2
[]
[Outputs]
  csv = true
[]
""")
gold(frames, 25, "wall_gran_out_state_0001.csv", False)
gold(frames, 50, "wall_gran_out_state_0002.csv", False)
