# LAMMPS fix wall/gran hooke/history 1000 500 50 50 0.4 1 zplane (lammps/in.wall_gran): a
# spinning sphere hits the floor obliquely; generated by generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 3
    ny = 3
    nz = 2
    xmin = -3
    xmax = 3
    ymin = -3
    ymax = 3
    zmin = -1
    zmax = 3
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '0 0 0.63'
    initial_velocities = '1.0 0.3 -2.0'
    initial_angular_velocity = '0.0 4.0 1.0'
    radius = 0.625
    density = 0.97784797035660498
    normal_stiffness = 1000
    normal_damping = 50
    tangential_stiffness = 500
    tangential_damping = 50
    friction = 0.4
    rescale_histories = false
    wall_points = '0 0 0'
    wall_normals = '0 0 1'
    skin = 0.3
    substeps = 25
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.025
  num_steps = 2
[]
[Outputs]
  csv = true
[]
