# LAMMPS fix wall/gran/region hooke/history 4000 NULL 100 NULL 0.5 1 with a cubic region
# rotating about z (lammps/in.wall_rotating): a unit sphere resting on the floor is dragged
# around by friction; generated by generate.py, gold from the dump
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 11
    ny = 11
    nz = 11
    xmin = -11
    xmax = 11
    ymin = -11
    ymax = 11
    zmin = -11
    zmax = 11
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '3 0 -5.5'
    radius = 0.5
    density = 1
    gravity = '0 0 -1'
    normal_stiffness = 4000
    normal_damping = 100
    tangential_stiffness = 1142.8571428571429
    tangential_damping = 50
    mass_scaled_damping = true
    friction = 0.5
    rescale_histories = false
    wall_points = '-6 0 0
                   6 0 0
                   0 -6 0
                   0 6 0
                   0 0 -6
                   0 0 6'
    wall_normals = '1 0 0
                    -1 0 0
                    0 1 0
                    0 -1 0
                    0 0 1
                    0 0 -1'
    wall_angular_velocity = '0 0 0.50265482457436694'
    skin = 0.15
    substeps = 500
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[VectorPostprocessors]
  [state]
    type = KokkosParticleState
    cloud = cloud
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 2.5
  num_steps = 4
[]
[Outputs]
  csv = true
[]
