#!/usr/bin/env python3
"""LAMMPS examples/pour/in.pour: 3000 unit spheres (density 1, LJ units) poured into a box
periodic in x and y onto a floor, gran/hooke/history 2000 NULL 50 NULL 0.5 0 (k_t = 2/7 k_n,
gamma_n = 50 on m_eff, no tangential damping, mu = 0.5), gravity 1 for 25 time units; then
gravity tilted to a 26-degree chute for 25 more, the bed sliding and rolling away on the flat
floor. LAMMPS's fix pour drops batches of 402 spheres (13% of the slab's volume) every 3.16
time units; here the same 3000 are inserted at the equivalent steady rate over the same
22.1 time units. The comparison is statistical: the number of spheres, the translational and
rotational kinetic energies, and the bed height against LAMMPS's log (log.pour.lammps, shipped
with LAMMPS). Stage 2 restarts from stage 1's checkpoint with the tilted gravity. The bed's
rotational energy grows to 200-250 here while LAMMPS's shipped log holds at 50-70; this is not
a model difference: started from the same settled bed (LAMMPS's, written out without contact
histories) LAMMPS gran/hooke/history, LAMMPS pair granular, and the module all spin up alike
(223, 293, 201 at the end), and LAMMPS's own pair granular continued through the run boundary
spins up too (233-279). The bed sits at the sliding threshold (mu = 0.5 against tan 26 =
0.49), and only gran/hooke/history continued with its stage-1 histories stays locked.
Usage: run.py [-n ranks] [dem-opt]"""
import csv, math, os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[1:]
ranks = 8
if args[:1] == ["-n"]:
    ranks = int(args[1])
    args = args[2:]
exe = args[0] if args else os.path.join(here, "../../../dem-opt")

N = 3000
k_n, gamma_n, mu = 2000.0, 50.0, 0.5
k_t = 2.0 / 7.0 * k_n
theta = math.radians(26)
batch = int(0.13 * 18 * 18 * 5 / (math.pi / 6))    # spheres per LAMMPS batch: 402
t_batch = math.sqrt(2 * 5 / 1.0)                   # a batch falls out of the slab in 3.16
t_pour = (N / batch - 1) * t_batch                 # the last batch is dropped at 22.1
rate = N / t_pour


def cloud(gravity, extra):
    return f"""[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '0 0 12.5'
    radius = 0.5
    density = 1
    gravity = '{gravity}'
    normal_stiffness = {k_n}
    normal_damping = {gamma_n}
    tangential_stiffness = {k_t:.17g}
    tangential_damping = 0
    mass_scaled_damping = true
    friction = {mu}
    rescale_histories = false
    wall_points = '0 0 0'
    wall_normals = '0 0 1'
    periodic = 'x y'
{extra}    skin = 0.2
    substeps = 100
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [num]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_particles
  []
  [ke]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = kinetic_energy
  []
  [erot]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = rotational_kinetic_energy
  []
  [height]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_z
  []
[]
"""


mesh = """[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 10
    ny = 10
    nz = 10
    xmin = -10
    xmax = 10
    ymin = -10
    ymax = 10
    zmin = -0.5
    zmax = 20
  []
[]
[Problem]
  solve = false
[]
"""
with open(os.path.join(here, "pour.i"), "w") as f:
    f.write(f"""# Stage 1 of LAMMPS examples/pour/in.pour: pouring 3000 spheres for 25 time units; generated
# by run.py, which also runs stage 2 (the chute) from this stage's checkpoint
""" + mesh + cloud("0 0 -1", f"""    insertion_box = '-9 -9 10
                     9 9 15'
    insertion_rate = {rate:.17g}
    insertion_end_time = {t_pour + 0.05:.17g}
    insertion_seed = 300719
""") + """[Executioner]
  type = Transient
  dt = 0.1
  num_steps = 250
[]
[Outputs]
  csv = true
  checkpoint = true
[]
""")
with open(os.path.join(here, "chute.i"), "w") as f:
    f.write(f"""# Stage 2 of LAMMPS examples/pour/in.pour: gravity tilted 26 degrees (fix gravity chute 26)
# for 25 time units from the poured bed; generated by run.py
[Problem]
  restart_file_base = pour_out_cp/0250
[]
""" + mesh.replace("[Problem]\n  solve = false\n[]\n", "") + cloud(f"{math.sin(theta):.17g} 0 {-math.cos(theta):.17g}", "") + """[Executioner]
  type = Transient
  dt = 0.1
  num_steps = 250
[]
[Outputs]
  csv = true
[]
""")
# The restart input keeps the mesh block and adds solve = false to its Problem block
s = open(os.path.join(here, "chute.i")).read().replace("[Problem]\n  restart_file_base = pour_out_cp/0250\n[]\n", "[Problem]\n  solve = false\n  restart_file_base = pour_out_cp/0250\n[]\n")
open(os.path.join(here, "chute.i"), "w").write(s)

for base in ("pour", "chute"):
    cmd = ["mpiexec", "-n", str(ranks), exe, "-i", base + ".i"] if ranks > 1 else [exe, "-i", base + ".i"]
    print(f"running {base} ...", flush=True)
    out = subprocess.run(cmd, cwd=here, capture_output=True, text=True)
    if out.returncode:
        print(out.stdout[-3000:], out.stderr[-2000:])
        sys.exit(1)

# LAMMPS thermo: step atoms ke c_1 (rotational ke) vol, every 1000 steps = 1 time unit
lammps = []
for line in open(os.path.join(here, "log.pour.lammps")):
    p = line.split()
    if len(p) == 5 and p[0].isdigit() and all(c in "0123456789.e-+" for c in p[2]):
        lammps.append((int(p[0]) / 1000, int(p[1]), float(p[2]), float(p[3])))
ours = [(float(q["time"]), int(float(q["num"])), float(q["ke"]), float(q["erot"]), float(q["height"]))
        for q in csv.DictReader(open(os.path.join(here, "pour_out.csv")))]
ours += [(25 + float(q["time"]) - 25, int(float(q["num"])), float(q["ke"]), float(q["erot"]), float(q["height"]))
         for q in csv.DictReader(open(os.path.join(here, "chute_out.csv"))) if float(q["time"]) > 25]
print(f"{'t':>5} {'N LAMMPS':>9} {'N MOOSE':>8} {'KE LAMMPS':>11} {'KE MOOSE':>11} {'Erot LAMMPS':>12} {'Erot MOOSE':>11}")
for t in (5, 10, 15, 20, 25, 30, 35, 40, 45, 50):
    l = next(q for q in lammps if abs(q[0] - t) < 1e-6)
    m = next(q for q in ours if abs(q[0] - t) < 1e-6)
    print(f"{t:5.0f} {l[1]:9d} {m[1]:8d} {l[2]:11.1f} {m[2]:11.1f} {l[3]:12.2f} {m[3]:11.2f}")
# The chute stage: the bed's acceleration from the kinetic energy, KE = 1/2 M (a (t - 25))^2
M = N * math.pi / 6
def accel(rows):
    pts = [(q[0] - 25, q[2]) for q in rows if q[0] >= 35]
    return sum(math.sqrt(2 * ke / M) / t for t, ke in pts) / len(pts)
print(f"chute: mean bed acceleration over t = 35-50: LAMMPS {accel(lammps):.4f}, MOOSE {accel(ours):.4f} "
      f"(g sin 26 = {math.sin(theta):.4f}; a rolling sphere alone: {5 / 7 * math.sin(theta):.4f})")
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, axs = plt.subplots(1, 2, figsize=(9, 3.8))
    axs[0].plot([q[0] for q in lammps], [q[2] for q in lammps], "k-", label="LAMMPS")
    axs[0].plot([q[0] for q in ours], [q[2] for q in ours], "r--", label="MOOSE")
    axs[0].set_xlabel("time"); axs[0].set_ylabel("kinetic energy"); axs[0].set_yscale("log")
    axs[1].plot([q[0] for q in lammps], [q[1] for q in lammps], "k-", label="LAMMPS (batches)")
    axs[1].plot([q[0] for q in ours], [q[1] for q in ours], "r--", label="MOOSE (steady rate)")
    axs[1].set_xlabel("time"); axs[1].set_ylabel("spheres")
    for ax in axs:
        ax.grid(alpha=0.3); ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(here, "pour.png"), dpi=130)
    print("plot: pour.png")
except ImportError:
    pass
