#!/usr/bin/env python3
"""LAMMPS examples/granular/in.pour.flatwall, reduced (in.pour.flatwall here, run with LAMMPS to
make log.pour.flatwall.lammps): 3000 spheres of diameter 0.5-1 (density 1, LJ units) poured
under gravity 10 onto a floor for 5 time units, pair granular hertz/material 1e5 1e3 0.3
(viscoelastic damping), mindlin NULL 1.0 0.5, rolling sds 500 200 0.5, the same on the floor.
The original's second material (JKR cohesion, linear tangential spring), its twisting
resistance, and its two cylindrical insertion regions are not represented. LAMMPS's fix pour
drops batches of ~1100 at t = 0, 1.2 and 3.2; here the 3000 are inserted at the equivalent
steady rate. Statistical comparison of count, kinetic energies, and bed height.
Usage: run.py [-n ranks] [dem-opt]"""
import csv, os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
args = sys.argv[1:]
ranks = 8
if args[:1] == ["-n"]:
    ranks = int(args[1])
    args = args[2:]
exe = args[0] if args else os.path.join(here, "../../../dem-opt")
N, t_pour = 3000, 3.2
with open(os.path.join(here, "pour_flatwall.i"), "w") as f:
    f.write(f"""# LAMMPS examples/granular/in.pour.flatwall (reduced) in the module; generated by run.py. The
# Hertz model with E = 1e5, nu = 0.3 is LAMMPS's hertz/material; normal_damping and
# tangential_damping are its viscoelastic gamma m_eff sqrt(r_eff overlap) dashpots (x_t = 1)
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 10
    ny = 10
    nz = 16
    xmax = 20
    ymax = 20
    zmax = 32
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '10 10 20'
    radius = 0.5
    density = 1
    gravity = '0 0 -10'
    contact_model = hertz
    youngs_modulus = 1e5
    poissons_ratio = 0.3
    normal_damping = 1e3
    tangential_damping = 1e3
    friction = 0.5
    rolling_stiffness = 500
    rolling_damping = 200
    rolling_friction = 0.5
    deformed_torque_arm = true
    wall_points = '0 0 0'
    wall_normals = '0 0 1'
    periodic = 'x y'
    insertion_box = '1 5 15
                     19 15 30'
    insertion_rate = {N / t_pour:.17g}
    insertion_radius_range = '0.25 0.5'
    insertion_end_time = {t_pour + 0.005:.17g}
    insertion_seed = 3123
    skin = 0.15
    substeps = 10
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [num]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = num_particles
  []
  [ke]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = kinetic_energy
  []
  [erot]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = rotational_kinetic_energy
  []
  [height]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_z
  []
[]
[Executioner]
  type = Transient
  dt = 0.01
  num_steps = 500
[]
[Outputs]
  csv = true
[]
""")
cmd = ["mpiexec", "-n", str(ranks), exe, "-i", "pour_flatwall.i"] if ranks > 1 else [exe, "-i", "pour_flatwall.i"]
out = subprocess.run(cmd, cwd=here, capture_output=True, text=True)
if out.returncode:
    print(out.stdout[-3000:], out.stderr[-2000:])
    sys.exit(1)
lammps = []
for line in open(os.path.join(here, "log.pour.flatwall.lammps")):
    p = line.split()
    if len(p) == 5 and p[0].isdigit() and p[1].isdigit():
        lammps.append((int(p[0]) / 1000, int(p[1]), float(p[2]), float(p[3]), float(p[4])))
ours = [(float(q["time"]), int(float(q["num"])), float(q["ke"]), float(q["erot"]), float(q["height"]))
        for q in csv.DictReader(open(os.path.join(here, "pour_flatwall_out.csv")))]
print(f"{'t':>4} {'N LAMMPS':>9} {'N MOOSE':>8} {'KE LAMMPS':>10} {'KE MOOSE':>10} {'Erot LAMMPS':>12} {'Erot MOOSE':>11} {'top LAMMPS':>11} {'top MOOSE':>10}")
for t in (0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5):
    l = next(q for q in lammps if abs(q[0] - t) < 1e-6)
    m = next(q for q in ours if abs(q[0] - t) < 1e-6)
    print(f"{t:4.1f} {l[1]:9d} {m[1]:8d} {l[2]:10.0f} {m[2]:10.0f} {l[3]:12.1f} {m[3]:11.1f} {l[4]:11.2f} {m[4]:10.2f}")
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(5.5, 3.8))
    ax.plot([q[0] for q in lammps], [q[2] for q in lammps], "k-", label="LAMMPS (batches)")
    ax.plot([q[0] for q in ours], [q[2] for q in ours], "r--", label="MOOSE (steady rate)")
    ax.set_xlabel("time"); ax.set_ylabel("kinetic energy")
    ax.grid(alpha=0.3); ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(here, "pour_flatwall.png"), dpi=130)
    print("plot: pour_flatwall.png")
except ImportError:
    pass
