#!/usr/bin/env python3
"""Granular column collapse in 2D (Lube et al. 2004; Lajeunesse et al. 2004): a rectangular column
of spheres of initial width L0 and height H0 = a L0 is released on a rough floor and spreads; the
runout (L_f - L0) / L0 scales as a for small aspect ratio and as a^(2/3) for large. Generates
the columns (hexagonal packing, slight jitter), runs them, measures the final runout and height
from the bed extent postprocessors, and plots. Usage: run.py [dem-opt] [aspect ratios...]"""
import csv, math, os, subprocess, sys, random

here = os.path.dirname(os.path.abspath(__file__))
exe = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "../../dem-opt")
aspects = [float(a) for a in sys.argv[2:]] or [0.5, 1.0, 2.0, 4.0]

r = 0.003                        # 6 mm beads
L0 = 0.12                        # column width: 20 diameters
mu, mu_r = 0.5, 0.3       # rolling resistance stands in for the roughness of real beads and floors
random.seed(1)


def column(H0):
    """Hexagonal packing of the column [0, L0] x [0, H0] against the left wall at x = 0"""
    dx, dy = 2 * r * 1.02, 2 * r * 1.02 * math.sqrt(3) / 2
    pts = []
    row = 0
    y = r * 1.05
    while y < H0 - r:
        x = r * 1.05 + (dx / 2 if row % 2 else 0)
        while x < L0 - r:
            pts.append((x + random.uniform(-1, 1) * 0.01 * r, y, 0))
            x += dx
        y += dy
        row += 1
    return pts


results = []
for a in aspects:
    H0 = a * L0
    pts = column(H0)
    width, height = max(3 * L0, 1.2 * (L0 + 6 * H0)), 1.3 * H0 + 0.05
    nx, ny = int(width / 0.05) + 1, int(height / 0.05) + 1
    base = f"collapse_a{a:g}"
    with open(os.path.join(here, base + ".i"), "w") as f:
        f.write(f"""# Column collapse, aspect ratio {a}: {len(pts)} beads, generated by run.py
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = {nx}
    ny = {ny}
    xmax = {width:.4f}
    ymax = {height:.4f}
  []
[]
[Problem]
  solve = false
[]
[UserObjects]
  [cloud]
    type = KokkosParticleCloud
    initial_positions = '{chr(10).join(f"{x:.6f} {y:.6f} {z}" for x, y, z in pts)}'
    radius = {r}
    density = 2500
    gravity = '0 -9.81 0'
    normal_stiffness = 1e5
    normal_damping = 2
    tangential_stiffness = 1e5
    tangential_damping = 2
    friction = {mu}
    rolling_stiffness = 1e5
    rolling_damping = 2
    rolling_friction = {mu_r}
    wall_boundaries = 'bottom left'
    skin = 0.0006
    substeps = 1000
    timestep_check = none
    execute_on = TIMESTEP_END
  []
[]
[Postprocessors]
  [runout]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_x
  []
  [height]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = max_y
  []
  [ke]
    type = KokkosParticleCloudValue
    cloud = cloud
    value = kinetic_energy
  []
[]
[VectorPostprocessors]
  [profile]
    type = KokkosParticleProfile
    cloud = cloud
    direction = x
    num_bins = {int(width / (4 * r))}
    execute_on = TIMESTEP_END
  []
[]
[Executioner]
  type = Transient
  dt = 0.01
  num_steps = {int(round(0.15 + 0.4 * math.sqrt(H0 / 9.81) * 12, 2) / 0.01)}
[]
[Outputs]
  csv = true
[]
""")
    t0 = subprocess.run([exe, "-i", base + ".i"], cwd=here, capture_output=True, text=True)
    if t0.returncode:
        print(t0.stdout[-2000:], t0.stderr[-2000:])
        sys.exit(1)
    rows = list(csv.DictReader(open(os.path.join(here, base + "_out.csv"))))
    Lf, Hf, ke = float(rows[-1]["runout"]), float(rows[-1]["height"]), float(rows[-1]["ke"])
    # The deposit's edge: the farthest slab (two diameters wide) still holding more than a
    # monolayer's worth of solid fraction; the farthest single bead is reported alongside
    last = int(float(rows[-1]["time"]) / 0.01 + 0.5)
    prof = list(csv.DictReader(open(os.path.join(here, f"{base}_out_profile_{last:04d}.csv"))))
    # A slab of width 4 r (two diameters) over the mesh height holds solid fraction
    # n (4/3 pi r^3) / (4 r height) with n beads; the deposit needs at least three
    threshold = 3 * 4.0 / 3.0 * math.pi * r**3 / (4 * r * height)
    edge = max(float(q["bin_center"]) + 2 * r for q in prof if float(q["solid_fraction"]) >= threshold)
    results.append((a, len(pts), (edge - L0) / L0, (Lf - L0) / L0, Hf / L0, ke))
    print(f"a = {a:g}: {len(pts)} beads, deposit runout (L_f - L0)/L0 = {(edge - L0) / L0:.3f} "
          f"(farthest bead {(Lf - L0) / L0:.3f}), H_f/L0 = {Hf / L0:.3f}, KE = {ke:.2e} J at t = {rows[-1]['time']} s")

# Lube et al. 2004 (2D channel): runout 1.2 a (a < 1.8), 1.9 a^(2/3) (a > 2.8)
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(5.5, 4.2))
    ax.loglog([q[0] for q in results], [q[2] for q in results], "o", label="DEM deposit edge (2D monolayer)")
    ax.loglog([q[0] for q in results], [q[3] for q in results], "x", color="gray", label="DEM farthest bead")
    aa = [0.3 * 1.15**i for i in range(30)]
    ax.loglog(aa, [1.2 * x for x in aa], "k--", label="Lube et al. 2004: 1.2 a (a < 1.8)")
    ax.loglog(aa, [1.9 * x**(2 / 3) for x in aa], "k:", label="Lube et al. 2004: 1.9 a^(2/3) (a > 2.8)")
    ax.set_xlabel("aspect ratio a = H0 / L0")
    ax.set_ylabel("runout (L_f - L0) / L0")
    ax.grid(alpha=0.3, which="both")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(os.path.join(here, "column_collapse.png"), dpi=130)
    print("plot: column_collapse.png")
except ImportError:
    pass
